---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go
spec:
  selector:
    matchLabels:
      app: go
  replicas: 1
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: go-project
        image: eu.gcr.io/{{PROJECT_ID}}/go-project
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
